// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwcW3270Lj-zH2SQokCGzlHF_LhpiweKI',
    appId: '1:1093574505987:web:92b2aa4ba06d6e25b08036',
    messagingSenderId: '1093574505987',
    projectId: 'agriculte-6bcfd',
    authDomain: 'agriculte-6bcfd.firebaseapp.com',
    databaseURL: 'https://agriculte-6bcfd-default-rtdb.firebaseio.com',
    storageBucket: 'agriculte-6bcfd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCe-ub15-9CaS5b8AFkew3h7VIPTStT2A',
    appId: '1:1093574505987:android:dbccd37951b13601b08036',
    messagingSenderId: '1093574505987',
    projectId: 'agriculte-6bcfd',
    databaseURL: 'https://agriculte-6bcfd-default-rtdb.firebaseio.com',
    storageBucket: 'agriculte-6bcfd.firebasestorage.app',
  );
}
